export const LANDING                    = '/login';
export const SIGN_UP                    = '/registrar';
export const SIGN_IN                    = '/login';
export const HOME                       = '/';
export const LINE                       = '/linha/:cidade/:itinerario';
export const SEARCH_BUS                 = '/linhas/campos-dos-goytacazes';
export const SHARE_LOCATION             = '/compartilhar-localizacao/campos-dos-goytacazes/:itinerario'; // cuidado ao mudar a routes [MapView e MapShare get windows.location.pathname[3] ]
export const ACCOUNT                    = '/conta';
export const PASSWORD_FORGET            = '/esqueci-senha';
export const CreateLine                 = '/cadastrar-linha';